In [1]:
"""Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named 
“FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, 
intercept and mean squared error. (Wherever required remove null values, convert categorical data into numeric data) (Print 
Output wherever required)"""

'Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named \n“FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, \nintercept and mean squared error. (Wherever required remove null values, convert categorical data into numeric data) (Print \nOutput wherever required)'

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

df = pd.read_csv("D:/dvc/py/csv files/FuelConsumptionCo2.csv")
df

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MAKE                      1067 non-null   object
 2   MODEL                     1067 non-null   object
 3   VEHICLECLASS              1067 non-null   object
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64
 6   TRANSMISSION              1067 non-null   object
 7   FUELTYPE                  1067 non-null   object
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 12  CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB

In [17]:
df.isna().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [18]:
x = df.iloc[:, 0:12]
print(x)
y = df["CO2EMISSIONS"]
print(y)

      MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4
1          2014  ACURA         ILX         COMPACT         2.4          4
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6
...         ...    ...         ...             ...         ...        ...
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7
1              M6        Z                  11.2                  7.7
2             AV7        Z                   6.0                  5.8
3             AS6        Z                  12.7                  9.1
4             AS6        Z                  12.1                  8.7
...           ...      ...                   ...                  ...
1062          AS6        X                  13.4                  9.8
1063          AS6        X                  13.2                  9.5
1064          AS6        X                  13.4                  9.8
1065          AS6        X                  12.9                  9.3
1066          AS6        X                  14.9                 10.2

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG
0                      8.5                        33
1                      9.6                        29
2                      5.9                        48
3                     11.1                        25
4                     10.6                        27
...                    ...                       ...
1062                  11.8                        24
1063                  11.5                        25
1064                  11.8                        24
1065                  11.3                        25
1066                  12.8                        22

[1067 rows x 12 columns]
0       196
1       221
2       136
3       255
4       244
       ...
1062    271
1063    264
1064    271
1065    260
1066    294
Name: CO2EMISSIONS, Length: 1067, dtype: int64

In [19]:
x = pd.get_dummies(x, drop_first=True)
x

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,MAKE_ASTON MARTIN,MAKE_AUDI,MAKE_BENTLEY,...,TRANSMISSION_AV,TRANSMISSION_AV6,TRANSMISSION_AV7,TRANSMISSION_AV8,TRANSMISSION_M5,TRANSMISSION_M6,TRANSMISSION_M7,FUELTYPE_E,FUELTYPE_X,FUELTYPE_Z
0,2014,2.0,4,9.9,6.7,8.5,33,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2014,2.4,4,11.2,7.7,9.6,29,False,False,False,...,False,False,False,False,False,True,False,False,False,True
2,2014,1.5,4,6.0,5.8,5.9,48,False,False,False,...,False,False,True,False,False,False,False,False,False,True
3,2014,3.5,6,12.7,9.1,11.1,25,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,2014,3.5,6,12.1,8.7,10.6,27,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,2014,3.0,6,13.4,9.8,11.8,24,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1063,2014,3.2,6,13.2,9.5,11.5,25,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1064,2014,3.0,6,13.4,9.8,11.8,24,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1065,2014,3.2,6,12.9,9.3,11.3,25,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1066,2014,3.2,6,14.9,10.2,12.8,22,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [20]:
x_train, x_test, y_train, y_test = train_test_split (x,y,train_size=0.85, random_state=48)
lr = LinearRegression()

lr.fit(x_train, y_train)
y_predicted = lr.predict(x_test)

c = lr.coef_
interc = lr.intercept_

print("mse = ", mean_squared_error(y_test, y_predicted))
print("r2 score  = ", r2_score(y_test, y_predicted))
print("coeficent c = ", c)
print("intercept point = ", interc)

mse =  95.91071417065969
r2 score  =  0.9781461457985804
coeficent c =  [-8.72784521e-15  3.40807779e+00  5.22953319e-01 -9.82167293e-01
 -2.97106051e+00  1.17712438e+01 -5.31522615e+00  5.41620037e+00
  4.44559579e+00  1.33814076e+01 -4.50597758e+00 -3.60915283e+00
 -3.04762155e+00 -1.41111889e+00 -6.46485728e+00 -6.26029695e+00
  7.48270231e+00  9.94302011e-01 -2.74215039e+00  6.44185528e+00
  3.87745921e+00 -6.77303141e+00 -2.43559709e+00  1.01246403e+00
 -4.09729152e-01  1.96359683e+01  5.55801262e+00 -3.55924976e-01
  1.59928673e+00  6.02961395e+00  5.23373960e+00 -4.40127496e+00
  2.35119629e+00  1.21261168e+00 -2.19963893e+00 -8.99066902e+00
 -4.89443248e+00  1.15435798e+01  4.97895373e+00  1.20585281e+01
  4.66787951e+00 -7.88386677e-01  9.31721351e+00  1.09742060e+00
 -4.51029773e+00 -2.00006537e+00  7.53347753e+00  3.22512476e+00
  4.87769335e+00 -2.19081036e+00  0.00000000e+00 -2.05578138e+00
 -7.10542736e-14 -3.46801725e+00 -2.67077681e+00 -5.32907052e-14
 -5.74090699e+00 -1.29945701e+00  1.56319402e-13  8.57617564e-01
 -3.35741831e+00  0.00000000e+00  7.71799625e-01 -7.10411255e-01
  1.98888681e+01  2.01542172e+01  3.94657485e+00 -1.56993152e+00
  2.97383551e+00 -1.30458242e+00 -8.96866251e+00 -6.62423803e+00
 -2.54340528e+00 -7.41711794e+00 -7.92919586e+00  7.71799625e-01
 -1.56993152e+00 -8.96866251e+00 -4.20834296e+00 -1.21583293e+01
 -1.21583293e+01 -3.68590555e-01 -3.68590555e-01  4.58761304e+00
 -3.68590555e-01  9.17316383e+00 -3.68590555e-01 -4.80371233e+00
 -1.29541718e+00 -2.15493745e+00  5.07845041e+00  9.23705556e-14
 -3.86466718e+00 -8.57602146e+00 -2.46458407e+00 -7.08717231e+00
 -3.43468902e+00 -7.99101553e+00 -7.00835110e+00 -3.55271368e-15
 -2.46458407e+00 -2.46458407e+00  8.45511282e+00 -3.48810173e+00
 -4.47662477e+00 -3.01980663e-14 -5.80361341e+00 -2.04478096e+00
 -3.53721010e+00 -3.15145677e+00 -7.12248440e+00  8.88676503e+00
  7.23426859e-02  7.23426859e-02  7.23426859e-02  7.10542736e-15
 -3.28049600e+00 -1.00098524e+01 -4.16801041e+00 -4.16801041e+00
 -7.71636517e+00 -2.86104715e+00 -1.12006238e+01 -2.86104715e+00
 -1.31168508e+01 -8.41738074e-01  3.22609655e+00  1.19000713e+00
 -4.60585019e+00 -9.08991986e-01  3.74034146e+00 -1.77230601e+01
  6.69116153e+01 -3.33382735e-01 -7.29687117e+00  1.43293417e+00
 -4.30277888e+00 -2.36893838e-14 -2.46458407e+00 -3.25433951e+00
 -8.88178420e-15 -4.15615582e+00 -5.35495831e+00 -2.40735855e+01
 -2.21427481e+00  2.81737433e-01  2.28864317e+01  4.39764288e+00
 -6.32749337e+00 -3.32721275e+00  1.10058172e+01  8.71574120e-01
 -4.78574868e+00 -2.78443757e+00 -1.89832387e+00  1.47644889e+00
 -7.38413139e+00 -7.28345880e+00 -9.20455115e+00 -2.49159832e+00
 -3.61157999e+00  6.20214712e+00  8.19408590e+00  3.29202765e+01
 -4.47933107e+00 -1.14029224e+01 -1.10592744e+01 -1.61154478e+01
  8.35518476e+00 -1.84892488e+01  2.86578577e+01  1.73667745e+01
  6.92452791e+00  8.91149557e+00  7.57334324e+00  9.76996262e-15
  1.11022302e-14  5.89905580e-01 -1.77635684e-15  8.71574120e-01
 -4.34499677e+00 -7.34481303e+00 -1.77635684e-15 -6.69470956e+00
 -1.10742403e+01 -6.03540469e+00 -8.42024941e+00 -4.59748016e+00
 -5.94546732e+00 -1.50401735e+00 -1.65194116e+00  6.53057229e-01
 -4.53391478e-01 -3.29147646e+00 -5.96551881e-01 -2.34915516e+00
  1.04109795e+00  5.23631977e-01 -1.29669454e+00 -5.40549622e+00
 -4.70357091e+00  5.51512775e+00  1.39155325e+00 -9.16708900e+00
 -4.04293996e+00 -4.04293996e+00  9.24515142e-01  1.34522979e+00
  5.77315973e-15 -8.85046754e+00 -8.69963134e+00  4.62943779e+00
 -1.22710825e+00  5.57879468e+00  3.41442757e+00 -1.14743152e+00
  6.29623020e+00 -3.78217364e+00  1.78754473e+00  2.97187122e+00
  8.07504102e-01 -4.13377883e+00 -3.01556729e-01 -4.13377883e+00
 -3.01556729e-01 -2.88876527e+00  1.84278470e+00 -6.60030953e-01
 -8.79806403e+00 -1.87298311e+01 -6.64651869e+00 -7.30714963e+00
  1.27180657e+01 -1.33184235e+01  8.13331483e-01  1.27539370e+01
  1.47960803e+01  4.01816749e+01 -1.00101685e+01 -7.37488239e+00
 -5.98927796e+00 -6.38804669e+00  7.00579475e-01 -5.99343623e+00
 -7.33340625e+00  1.71481627e+01  9.40668149e+00  1.79985178e+01
  9.89078948e-01  2.96552866e-01 -4.81022859e+00 -4.77597485e+00
  2.36148729e+00  5.80738409e+00 -1.36835725e+00  1.76682123e+01
  1.49963102e+00 -6.05071548e-15 -3.14891925e+00  1.12605397e+01
 -7.40672310e+00 -1.05460139e+01 -5.92799512e+00 -9.52831533e+00
 -5.82977839e+00 -3.14983836e+00 -5.71816339e+00  2.05391260e-15
 -8.16714096e+00 -1.02110364e-14 -7.56033806e+00 -6.12555182e+00
 -7.56033806e+00 -6.12555182e+00  3.54341361e+00 -3.04448023e+00
  1.42108547e-14  9.04933789e+00 -2.92738187e+00 -1.25087355e+00
 -7.68914992e+00 -3.73884775e+00 -4.39947870e+00  1.08649816e+01
  1.10590242e+01 -4.08740786e+00  2.46055750e+00  3.21025634e+00
 -1.02177743e+01  3.47772012e+01 -1.44004471e+01 -1.33086678e-01
  1.47469445e+01  5.62082617e-01  1.27914737e+00  1.00071186e+01
 -5.75684381e+00 -3.05357142e+00 -5.67862178e+00 -4.19135665e+00
 -2.17888051e+00  1.89994003e+00  1.25416370e+00  3.29664183e+00
 -8.82688169e+00 -1.00617014e+01  9.79602716e+00  1.58801032e+01
 -5.67486085e+00 -9.22048916e-01 -4.05031905e+00 -7.04185845e+00
  4.95089575e+00 -4.81770781e+00 -6.89987605e-03  2.86559270e+01
  9.93001645e+00 -1.01030295e-14 -8.43769499e-15  3.50310744e+00
 -3.70433844e+00 -9.88487361e+00 -1.07101401e+01 -6.59064081e+00
  4.70769785e-01 -3.66341934e+00  5.27858564e+00  9.56431960e+00
 -2.13027431e+00 -1.37629206e-01  2.75611554e+00 -3.90626568e+00
  6.02926404e+00  6.02926404e+00 -2.04447465e+00  2.70428192e+00
  6.78503301e+00 -2.92927532e+00  1.02933098e+00 -7.61314878e+00
  6.32827124e-15  2.22044605e-16  3.36896391e+01 -3.25046337e+00
  6.14214083e-15  3.63042929e-14 -7.94778640e+00 -7.55197816e-01
 -7.55197816e-01  1.83774341e+01  1.39148291e+01  1.42735072e+01
  1.41823311e+01  1.28628180e+01  1.20083219e+00 -8.24842645e+00
  1.07247405e+01  8.12049916e+00 -3.31477326e+00 -4.56475790e-03
 -9.10382880e-15  4.35488185e+00  4.69918822e+00  2.92103146e+00
 -9.52339217e+00 -8.90145101e+00  6.31885076e+00 -3.77587997e+00
 -2.28136694e+00 -1.22512288e+01 -1.75129004e+01 -1.39523676e+01
 -1.48734600e+01 -5.78564729e+00 -2.24124105e-14 -2.86104379e+00
 -9.41343900e-01 -2.07298313e+00 -8.79429187e-01 -8.79926805e+00
 -8.40633617e+00 -5.22560597e+00 -5.00599407e+00 -8.31644509e+00
 -5.30035046e+00 -5.19228743e+00 -4.80244226e+00 -5.53598237e+00
  1.29473199e+01 -9.35862139e-15  3.35826708e+00  8.07504102e-01
 -4.13377883e+00 -3.01556729e-01 -4.13377883e+00 -3.01556729e-01
  5.77315973e-15  8.20994734e+00  7.03730741e+00  9.53111299e-01
 -8.21565038e-15 -4.81654770e+00 -3.79460658e+00 -1.39888101e-14
 -1.28543779e+00 -6.86541227e+00 -4.04069672e+00 -1.31852515e+01
 -2.01693778e+00 -8.54906863e+00  2.03346208e+00  6.06729258e+00
  1.06581410e-14 -3.43380171e+00 -3.43380171e+00 -7.32479374e+00
  1.58114627e+01  1.12379333e+00  1.70879926e+00  2.25845379e+00
  1.70879926e+00 -6.95528942e-01 -1.65798141e+01  5.00468852e+00
  5.96041034e+00  6.06985062e+00 -1.17683641e-14  3.53656896e+00
  3.30890929e+00  4.18868565e+00 -3.44752891e+00 -2.08673336e+00
  9.99200722e-15 -5.99690969e+00  2.73626949e+01 -7.12388853e+00
 -7.19562553e+00  1.42507007e+00 -2.55337235e+00 -1.30131079e+00
  5.88418203e-15 -1.16677138e+01  2.06139937e+01  1.48610378e+00
  1.71195650e+00  4.14628793e+00  1.05197266e+01  2.70584072e+01
 -1.79856130e-14 -1.08049477e+01 -8.34916878e+00 -9.00053989e+00
  9.40213389e+00 -4.52745145e+00 -7.54964182e+00 -7.10437338e+00
  2.03204848e+00  7.04276958e-01 -5.00450376e-14 -8.41819628e-01
 -1.06088004e+00 -3.64260334e+00  1.63975082e+00  3.87725830e+00
 -1.62247675e+00  1.63975082e+00 -6.03167673e-01  1.61503073e+00
 -7.51711835e+00  1.39210769e+01 -2.62012634e-14 -7.89556729e+00
 -1.04516153e+01  9.24515142e-01 -6.72256847e-15 -8.42346843e+00
  8.69739801e+00  4.15363098e+00  3.85652493e+00  8.40029196e+00
 -7.58634816e+00 -6.00947162e+00  6.47178726e+01  7.07194357e+01
  3.14613802e+01 -1.38338029e+00  2.43156190e-14  5.38901898e+00
 -6.11436086e+00 -8.13851670e+00  9.49226599e+00 -1.40577210e-01
  2.23231396e+00  4.92855815e-01 -2.29083885e+00 -2.66453526e-15
  2.27679088e+00 -7.36073446e+00 -6.78604013e+00  6.10979423e+00
  3.90006847e+00  2.45711220e+00 -1.01244076e+01 -3.03373601e+00
 -3.29341192e+00 -3.03295051e+00 -4.21759183e+00  1.05200250e+01
  8.78847208e+00  1.94554829e+01  2.23939436e+01 -1.78216607e+00
 -1.39406173e-14  3.37135708e+00  3.91988901e+00 -5.55107529e+00
 -3.79218999e+00  3.70756365e+00  1.52318721e+00 -6.76927369e+00
 -4.46128003e+00  3.37135708e+00  3.91988901e+00  3.66399813e+00
 -5.15448613e+00 -8.79216315e+00 -7.47574802e+00 -2.25856007e+00
 -2.18349842e+00 -4.34368435e+00 -2.34405891e-01 -9.25362502e+00
  7.56698365e+00  7.87348510e+00 -1.46044650e+01 -3.01980663e-14
 -1.37909809e+00 -7.33888799e+00 -2.62660684e+00  7.85677946e-15
  1.56329076e+01  1.92207361e-15  1.69715738e+00  3.88315130e-01
 -1.89977299e+00  1.96283961e-14 -7.03724720e+00 -4.88498131e-15
 -3.68886402e+00  7.79467606e+00  3.03910982e+00  9.68839812e+00
  4.17593592e+00 -4.31294955e+00 -2.31432862e+00  4.17593592e+00
 -7.38135587e+00 -5.52679277e+00 -1.65717040e+00 -6.99953997e+00
 -6.54018925e+00 -5.22525002e+00 -8.39545096e-01  6.38582321e-01
  3.23097152e+00 -2.13791279e+00  4.62767333e+00 -7.49585019e+00
 -5.45337206e+00  1.11270587e+01  1.32853970e+01  4.41104178e+00
  3.98630465e+00  8.58260277e+00 -1.03969800e+01 -5.02502856e+00
 -5.28890275e+00 -2.14633986e+00 -8.03141423e+00 -5.07328456e+00
 -1.08439009e+01 -9.81438875e+00  3.14327276e-02  4.23787212e-01
 -7.48238253e+00 -1.79230056e+01  1.93164760e+01  1.91513472e-14
  1.06952348e+01 -4.78649056e+00  2.87768285e+01  2.43826947e+01
  6.23696653e+00  5.40196061e+00  5.32996297e+00  5.91496889e+00
 -6.56116596e-01  3.97699495e+00 -1.75918561e+00 -1.58793475e+00
  2.49835585e+01  3.55868309e-01 -3.80494202e-01  2.38349519e+00
 -4.96239693e+00 -2.88952503e+00 -7.20644656e+00 -7.14410771e+00
 -8.16360909e+00 -6.35320557e+00 -7.20644656e+00 -7.26878541e+00
 -1.59872116e-14 -5.38965776e+00 -6.60456714e+00 -4.57718480e+00
  3.79158899e+00  1.98709398e+00  2.67879774e-01  1.39377035e-14
  7.45102685e+00  2.20339520e+01 -1.26913819e+01 -1.35801704e+01
 -7.43849426e-15  2.04808954e+00  1.12698829e+01  1.08486357e+00
  9.76198181e-01 -2.95059210e+00 -5.93688169e+00 -6.59751264e+00
  1.15109271e+01  1.19904087e-14  9.62746210e+00 -9.61869885e+00
 -4.59901671e+00 -7.87244465e+00 -2.66453526e-15 -1.06131852e+01
 -2.61169201e+00  1.97974168e-01 -8.18877564e+00  4.53837438e-01
  1.30447871e+00 -2.55153850e+00  1.49963102e+00 -2.80367394e+00
 -5.50707468e+00 -1.15484588e+01 -8.15420109e+00 -2.02208921e+00
  1.45119226e+01  2.08166817e-16  4.66787951e+00 -1.20538704e+01
  1.37146118e+00  5.21564448e+00  5.40144592e+00  3.12064143e+00
  4.31332709e+00  3.61531708e+00 -9.75204331e+00 -5.26276365e-01
  2.43902409e+01 -1.82568688e+00  2.40611581e+00  7.69900785e-01
  5.17898135e+00  3.91167459e+00 -5.59613111e-01  4.36506313e-01
 -1.25834121e+00 -5.41091941e-01 -3.15303339e-14  6.90349652e+00
  2.08807199e+00  7.00171325e+00  1.93308581e+00  1.77809963e+00
  1.77809963e+00 -1.95579217e+00 -9.44456282e+00  1.34328739e+00
 -1.59711404e+00  1.34328739e+00 -1.59711404e+00  1.27092158e+01
 -1.43218770e-14 -2.28520994e+00 -1.77956792e-01 -2.50339917e+00
  7.79946626e+00  6.28797250e+00 -5.87541506e+00 -5.87541506e+00
 -2.72715240e-01  1.04434180e+01 -5.87541506e+00 -5.93775392e+00
 -1.37036998e+00 -4.20420580e+00 -4.97889201e+00  2.44197572e+01
 -1.28154376e+01 -7.93505627e+00  3.35416511e+00 -4.54376703e+00
  5.85005925e-01 -1.40929497e+00 -8.44424206e+00 -5.02749973e+00
  1.87787048e+00 -6.54528409e+00  2.34307326e+00 -2.65349108e-01
 -3.57366208e+00 -6.97137744e+00  1.30696446e+00 -3.00234135e-01
  1.41745930e+01  2.42556384e+01  1.54272598e+00 -1.55559731e-01
 -1.90383514e+01  1.20127563e+00 -1.38097711e+00  1.20585281e+01
  7.74971540e+00  3.28173933e+00  1.01050331e-01 -8.38375496e-01
  2.09352128e-01  1.44594997e+00 -3.56044962e+00 -1.78216607e+00
  8.71212007e+00  9.74831814e-01  1.26979453e+01 -4.28643898e+00
  1.01050331e-01  1.37607966e+00  2.59587439e-01 -1.16771687e+02
 -2.89731441e+01 -2.92623684e+01]
intercept point =  323.68533412834074